In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import time
import os

In [2]:
# Lendo CSV..
dataframe = pd.read_csv( '/home/math/workspace/HomeC.csv', low_memory=False )

dataframe

,time,use [kW],gen [kW],House overall [kW],Dishwasher [kW],Furnace 1 [kW],Furnace 2 [kW],Home office [kW],Fridge [kW],Wine cellar [kW],...,visibility,summary,apparentTemperature,pressure,windSpeed,cloudCover,windBearing,precipIntensity,dewPoint,precipProbability
0,1451624400,0.932833,0.003483,0.932833,0.000033,0.020700,0.061917,0.442633,0.124150,0.006983,...,10.00,Clear,29.26,1016.91,9.18,cloudCover,282.0,0.0000,24.40,0.00
1,1451624401,0.934333,0.003467,0.934333,0.000000,0.020717,0.063817,0.444067,0.124000,0.006983,...,10.00,Clear,29.26,1016.91,9.18,cloudCover,282.0,0.0000,24.40,0.00
2,1451624402,0.931817,0.003467,0.931817,0.000017,0.020700,0.062317,0.446067,0.123533,0.006983,...,10.00,Clear,29.26,1016.91,9.18,cloudCover,282.0,0.0000,24.40,0.00
3,1451624403,1.022050,0.003483,1.022050,0.000017,0.106900,0.068517,0.446583,0.123133,0.006983,...,10.00,Clear,29.26,1016.91,9.18,cloudCover,282.0,0.0000,24.40,0.00
4,1451624404,1.139400,0.003467,1.139400,0.000133,0.236933,0.063983,0.446533,0.122850,0.006850,...,10.00,Clear,29.26,1016.91,9.18,cloudCover,282.0,0.0000,24.40,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503906,1452128306,1.599333,0.003233,1.599333,0.000050,0.104017,0.625033,0.041750,0.005233,0.008433,...,8.74,Light Rain,29.45,1011.49,6.72,0.31,186.0,0.0101,31.27,0.51
503907,1452128307,1.924267,0.003217,1.924267,0.000033,0.422383,0.637733,0.042033,0.004983,0.008467,...,8.74,Light Rain,29.45,1011.49,6.72,0.31,186.0,0.0101,31.27,0.51
503908,1452128308,1.978200,0.003217,1.978200,0.000050,0.495667,0.620367,0.042100,0.005333,0.008233,...,8.74,Light Rain,29.45,1011.49,6.72,0.31,186.0,0.0101,31.27,0.51
503909,1452128309,1.990950,0.003233,1.990950,0.000050,0.494700,0.634133,0.042100,0.004917,0.008133,...,8.74,Light Rain,29.45,1011.49,6.72,0.31,186.0,0.0101,31.27,0.51
503910,\,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Somando consumo de energia de todas as cozinhas..
dataframe['KW_kitchen'] = dataframe['Kitchen 12 [kW]'] + dataframe['Kitchen 14 [kW]'] + dataframe['Kitchen 38 [kW]']

In [4]:
# Renomeando colunas..
dataframe.rename( columns={
      'temperature': 'C_temperature',
      'use [kW]': 'KW_use',
      'Home office [kW]': 'KW_home_office',
      'Living room [kW]': 'KW_living_room',
      'Wine cellar [kW]': 'KW_wine_cellar',
      'Garage door [kW]': 'KW_garage_door',
      'Barn [kW]': 'KW_barn'
    }, 
    inplace=True 
)

In [5]:
format_date = '%Y-%m-%d %H:%M:%S'

initial_date = time.strftime( format_date, time.localtime( int( dataframe.loc[0, 'time'] ) ) )
index = pd.date_range( initial_date, periods=len( dataframe ), freq='min' )
dataframe = dataframe.set_index( pd.DatetimeIndex( data=index, name='datetime' ) ).groupby( pd.Grouper( freq='D' ) ).mean()

dataframe

,KW_use,gen [kW],House overall [kW],Dishwasher [kW],Furnace 1 [kW],Furnace 2 [kW],KW_home_office,Fridge [kW],KW_wine_cellar,KW_garage_door,...,humidity,visibility,apparentTemperature,pressure,windSpeed,windBearing,precipIntensity,dewPoint,precipProbability,KW_kitchen
datetime,,,,,,,,,,,,,,,,,,,,,
2016-01-01,1.283848,0.014617,1.283848,0.047245,0.207469,0.226135,0.068333,0.082729,0.023781,0.013289,...,0.635063,9.742222,29.350778,1014.650317,7.438206,264.873016,0.000101,24.207857,0.001841,0.014171
2016-01-02,1.270038,0.052820,1.270038,0.061763,0.220191,0.242775,0.102638,0.060978,0.016720,0.013340,...,0.573125,9.988722,24.641097,1014.498583,8.015903,260.101389,0.000000,18.306500,0.000000,0.011023
2016-01-03,1.119718,0.051461,1.119718,0.055359,0.177222,0.253681,0.135872,0.052980,0.022900,0.013562,...,0.624819,9.986056,26.743792,1009.340069,7.518236,228.416667,0.000000,21.588542,0.000000,0.013151
2016-01-04,1.045337,0.075341,1.045337,0.040896,0.223468,0.222587,0.122884,0.050717,0.016559,0.013329,...,0.585625,9.819000,8.191292,1017.965167,11.860861,314.373611,0.000000,7.967125,0.000000,0.011925
2016-01-05,1.069794,0.102862,1.069794,0.050674,0.295407,0.270894,0.094327,0.053817,0.019423,0.013750,...,0.549319,9.996264,4.265736,1034.708486,5.842278,294.469444,0.000000,-1.637819,0.000000,0.005924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-12,1.102570,0.005703,1.102570,0.000074,0.188663,0.195614,0.041438,0.050022,0.027527,0.015179,...,0.781236,8.188535,40.340576,1013.365444,10.267819,225.908333,0.001077,37.833715,0.035625,0.008669
2016-12-13,0.739099,0.029159,0.739099,0.048935,0.132444,0.204447,0.041296,0.051474,0.023043,0.013306,...,0.615868,9.892333,27.743583,1015.519424,9.330410,297.201389,0.000000,23.031917,0.000000,0.005875
2016-12-14,0.811981,0.036280,0.811981,0.000067,0.157886,0.210741,0.041326,0.053800,0.031504,0.014746,...,0.813313,7.128625,26.868347,1012.005111,3.838604,174.715972,0.009751,24.777035,0.218493,0.003977
2016-12-15,0.989566,0.041258,0.989566,0.050761,0.264648,0.308904,0.042016,0.042467,0.019861,0.013026,...,0.738667,9.010736,25.160625,1000.514111,10.926840,253.057639,0.001166,25.493431,0.044611,0.004141
2016-12-16,1.347043,0.003909,1.347043,0.000081,0.291939,0.478373,0.041952,0.035290,0.046576,0.016216,...,0.844444,8.452222,29.551111,1011.637778,7.147778,189.888889,0.010294,31.168889,0.510000,0.000718

In [6]:
# Removendo Nan e Null..
dataframe = dataframe.dropna()

,KW_use,gen [kW],House overall [kW],Dishwasher [kW],Furnace 1 [kW],Furnace 2 [kW],KW_home_office,Fridge [kW],KW_wine_cellar,KW_garage_door,...,humidity,visibility,apparentTemperature,pressure,windSpeed,windBearing,precipIntensity,dewPoint,precipProbability,KW_kitchen
datetime,,,,,,,,,,,,,,,,,,,,,
2016-01-01,1.283848,0.014617,1.283848,0.047245,0.207469,0.226135,0.068333,0.082729,0.023781,0.013289,...,0.635063,9.742222,29.350778,1014.650317,7.438206,264.873016,0.000101,24.207857,0.001841,0.014171
2016-01-02,1.270038,0.052820,1.270038,0.061763,0.220191,0.242775,0.102638,0.060978,0.016720,0.013340,...,0.573125,9.988722,24.641097,1014.498583,8.015903,260.101389,0.000000,18.306500,0.000000,0.011023
2016-01-03,1.119718,0.051461,1.119718,0.055359,0.177222,0.253681,0.135872,0.052980,0.022900,0.013562,...,0.624819,9.986056,26.743792,1009.340069,7.518236,228.416667,0.000000,21.588542,0.000000,0.013151
2016-01-04,1.045337,0.075341,1.045337,0.040896,0.223468,0.222587,0.122884,0.050717,0.016559,0.013329,...,0.585625,9.819000,8.191292,1017.965167,11.860861,314.373611,0.000000,7.967125,0.000000,0.011925
2016-01-05,1.069794,0.102862,1.069794,0.050674,0.295407,0.270894,0.094327,0.053817,0.019423,0.013750,...,0.549319,9.996264,4.265736,1034.708486,5.842278,294.469444,0.000000,-1.637819,0.000000,0.005924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-12,1.102570,0.005703,1.102570,0.000074,0.188663,0.195614,0.041438,0.050022,0.027527,0.015179,...,0.781236,8.188535,40.340576,1013.365444,10.267819,225.908333,0.001077,37.833715,0.035625,0.008669
2016-12-13,0.739099,0.029159,0.739099,0.048935,0.132444,0.204447,0.041296,0.051474,0.023043,0.013306,...,0.615868,9.892333,27.743583,1015.519424,9.330410,297.201389,0.000000,23.031917,0.000000,0.005875
2016-12-14,0.811981,0.036280,0.811981,0.000067,0.157886,0.210741,0.041326,0.053800,0.031504,0.014746,...,0.813313,7.128625,26.868347,1012.005111,3.838604,174.715972,0.009751,24.777035,0.218493,0.003977
2016-12-15,0.989566,0.041258,0.989566,0.050761,0.264648,0.308904,0.042016,0.042467,0.019861,0.013026,...,0.738667,9.010736,25.160625,1000.514111,10.926840,253.057639,0.001166,25.493431,0.044611,0.004141
2016-12-16,1.347043,0.003909,1.347043,0.000081,0.291939,0.478373,0.041952,0.035290,0.046576,0.016216,...,0.844444,8.452222,29.551111,1011.637778,7.147778,189.888889,0.010294,31.168889,0.510000,0.000718

In [7]:
# Removendo colunas que não serão utilizadas..
del dataframe['House overall [kW]']
del dataframe['apparentTemperature']
del dataframe['Solar [kW]']
del dataframe['humidity']
del dataframe['visibility']
del dataframe['pressure']
del dataframe['windSpeed']
del dataframe['windBearing']
del dataframe['precipIntensity']
del dataframe['dewPoint']
del dataframe['precipProbability']

# Removendo colunas de eletrodomésticos..
del dataframe['gen [kW]']
del dataframe['Dishwasher [kW]']
del dataframe['Furnace 1 [kW]']
del dataframe['Furnace 2 [kW]']
del dataframe['Fridge [kW]']
del dataframe['Well [kW]']
del dataframe['Microwave [kW]']

# Deletando colunas com nomes antigos..
del dataframe['Kitchen 12 [kW]']
del dataframe['Kitchen 14 [kW]']
del dataframe['Kitchen 38 [kW]']

dataframe

,KW_use,KW_home_office,KW_wine_cellar,KW_garage_door,KW_barn,KW_living_room,C_temperature,KW_kitchen
datetime,,,,,,,,
2016-01-01,1.283848,0.068333,0.023781,0.013289,0.083142,0.078428,35.373540,0.014171
2016-01-02,1.270038,0.102638,0.016720,0.013340,0.128887,0.042569,31.767431,0.011023
2016-01-03,1.119718,0.135872,0.022900,0.013562,0.102647,0.028892,33.182181,0.013151
2016-01-04,1.045337,0.122884,0.016559,0.013329,0.032467,0.057649,20.319653,0.011925
2016-01-05,1.069794,0.094327,0.019423,0.013750,0.033895,0.030561,12.145417,0.005924
...,...,...,...,...,...,...,...,...
2016-12-12,1.102570,0.041438,0.027527,0.015179,0.032547,0.093904,44.601062,0.008669
2016-12-13,0.739099,0.041296,0.023043,0.013306,0.033972,0.032586,34.906104,0.005875
2016-12-14,0.811981,0.041326,0.031504,0.014746,0.033243,0.063411,29.930194,0.003977
2016-12-15,0.989566,0.042016,0.019861,0.013026,0.031650,0.028108,33.048389,0.004141
2016-12-16,1.347043,0.041952,0.046576,0.016216,0.031875,0.034240,35.427222,0.000718

In [9]:
# Reposicionando colunas..
dataframe = dataframe[['C_temperature', 'KW_use', 'KW_kitchen', 'KW_living_room', 'KW_home_office', 'KW_wine_cellar', 'KW_barn', 'KW_garage_door']]

dataframe

,C_temperature,KW_use,KW_kitchen,KW_living_room,KW_home_office,KW_wine_cellar,KW_barn,KW_garage_door
datetime,,,,,,,,
2016-01-01,35.373540,1.283848,0.014171,0.078428,0.068333,0.023781,0.083142,0.013289
2016-01-02,31.767431,1.270038,0.011023,0.042569,0.102638,0.016720,0.128887,0.013340
2016-01-03,33.182181,1.119718,0.013151,0.028892,0.135872,0.022900,0.102647,0.013562
2016-01-04,20.319653,1.045337,0.011925,0.057649,0.122884,0.016559,0.032467,0.013329
2016-01-05,12.145417,1.069794,0.005924,0.030561,0.094327,0.019423,0.033895,0.013750
...,...,...,...,...,...,...,...,...
2016-12-12,44.601062,1.102570,0.008669,0.093904,0.041438,0.027527,0.032547,0.015179
2016-12-13,34.906104,0.739099,0.005875,0.032586,0.041296,0.023043,0.033972,0.013306
2016-12-14,29.930194,0.811981,0.003977,0.063411,0.041326,0.031504,0.033243,0.014746
2016-12-15,33.048389,0.989566,0.004141,0.028108,0.042016,0.019861,0.031650,0.013026
2016-12-16,35.427222,1.347043,0.000718,0.034240,0.041952,0.046576,0.031875,0.016216